from setuptools import setup, find_packages

setup(
    name="primarch-py",
    version="1.0.0",
    description="Python SDK for Primarch AI Platform",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    author="Primarch AI",
    author_email="sdk@primarch.ai",
    url="https://github.com/primarch-ai/primarch-py",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.8",
    install_requires=[
        "httpx>=0.24.0",
        "pydantic>=2.0.0",
        "typing-extensions>=4.5.0",
        "tenacity>=8.0.0",
        "opentelemetry-api>=1.15.0",
        "opentelemetry-sdk>=1.15.0",
    ],
    extras_require={
        "dev": [
            "pytest>=7.0.0",
            "pytest-cov>=4.0.0",
            "black>=23.0.0",
            "isort>=5.12.0",
            "mypy>=1.5.0",
            "pre-commit>=3.0.0",
        ],
        "async": ["aiohttp>=3.8.0"],
        "streaming": ["websockets>=11.0.0"],
    },
    classifiers=[
        "Development Status :: 5 - Production/Stable",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
    keywords="ai llm api sdk primarch machine-learning",
    project_urls={
        "Bug Tracker": "https://github.com/primarch-ai/primarch-py/issues",
        "Documentation": "https://docs.primarch.ai/python-sdk",
        "Source Code": "https://github.com/primarch-ai/primarch-py",
        "Changelog": "https://github.com/primarch-ai/primarch-py/blob/main/CHANGELOG.md",
    },
)
