
blank_issues_enabled: false
contact_links:
  - name: 🔒 Security Vulnerability (Private)
    url: mailto:security@company.com
    about: Report security vulnerabilities privately
  - name: 💬 General Discussion
    url: https://github.com/Empire325Marketing/agent-orchestration-ops/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://github.com/Empire325Marketing/agent-orchestration-ops/wiki
    about: Browse our documentation and guides
