
name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees:
  - Empire325Marketing

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: input
    id: title
    attributes:
      label: Feature Title
      description: A clear and concise title for the feature
      placeholder: Brief title of the feature
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Describe the problem or need this feature addresses
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution
      placeholder: Detailed description of the proposed feature
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Any alternative solutions you've considered
      placeholder: Other approaches you've thought about

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature?
      options:
        - Critical (Blocking current work)
        - High (Important for upcoming work)
        - Medium (Would be nice to have)
        - Low (Future consideration)
    validations:
      required: true

  - type: checkboxes
    id: impact
    attributes:
      label: Impact Areas
      description: Which areas would this feature impact?
      options:
        - label: User Experience
        - label: Performance
        - label: Security
        - label: Scalability
        - label: Maintainability
        - label: Documentation
        - label: Testing

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: What criteria must be met for this feature to be considered complete?
      placeholder: |
        - [ ] Criterion 1
        - [ ] Criterion 2
        - [ ] Criterion 3

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any additional context about the feature
      placeholder: Mockups, examples, related features, etc.
