
name: 🔒 Security Vulnerability
description: Report a security vulnerability (Please use private reporting for sensitive issues)
title: "[SECURITY] "
labels: ["security", "critical"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ⚠️ **IMPORTANT**: If this is a sensitive security vulnerability, please use GitHub's private vulnerability reporting feature instead of creating a public issue.
        
        For non-sensitive security improvements or questions, you can use this template.

  - type: dropdown
    id: type
    attributes:
      label: Vulnerability Type
      description: What type of security issue is this?
      options:
        - Authentication/Authorization
        - Input Validation
        - SQL Injection
        - Cross-Site Scripting (XSS)
        - Cross-Site Request Forgery (CSRF)
        - Insecure Direct Object Reference
        - Security Misconfiguration
        - Sensitive Data Exposure
        - Insufficient Logging/Monitoring
        - Dependency Vulnerability
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity Level
      description: How severe is this vulnerability?
      options:
        - Critical (Immediate threat)
        - High (Significant risk)
        - Medium (Moderate risk)
        - Low (Minor risk)
        - Informational
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Vulnerability Description
      description: Provide a clear description of the vulnerability
      placeholder: Describe the security issue...
    validations:
      required: true

  - type: textarea
    id: impact
    attributes:
      label: Potential Impact
      description: What could an attacker achieve by exploiting this vulnerability?
      placeholder: |
        - Data breach
        - Unauthorized access
        - System compromise
        - etc.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How can this vulnerability be reproduced? (Omit sensitive details)
      placeholder: |
        1. Navigate to...
        2. Enter payload...
        3. Observe result...

  - type: textarea
    id: mitigation
    attributes:
      label: Suggested Mitigation
      description: How do you suggest fixing this vulnerability?
      placeholder: |
        - Implement input validation
        - Add authentication checks
        - Update dependencies
        - etc.

  - type: textarea
    id: environment
    attributes:
      label: Affected Environment
      description: Which environments are affected?
      placeholder: |
        - Production: Yes/No
        - Staging: Yes/No
        - Development: Yes/No
        - Version: x.x.x

  - type: textarea
    id: references
    attributes:
      label: References
      description: Any relevant security advisories, CVEs, or documentation
      placeholder: |
        - CVE-XXXX-XXXX
        - https://example.com/security-advisory
        - OWASP reference

  - type: checkboxes
    id: disclosure
    attributes:
      label: Responsible Disclosure
      description: Please confirm your approach to disclosure
      options:
        - label: I am following responsible disclosure practices
          required: true
        - label: I have not shared this vulnerability publicly
          required: true
        - label: I understand this issue will be handled with appropriate priority
          required: true

  - type: textarea
    id: contact
    attributes:
      label: Contact Information
      description: How can we reach you for follow-up? (Optional)
      placeholder: email@example.com (for coordination purposes only)

  - type: markdown
    attributes:
      value: |
        ---
        **Security Team Response**: We take security vulnerabilities seriously and will respond to this report within 24-48 hours. Thank you for helping us keep our systems secure.
