
name: production
url: https://agent-orchestration-ops.com
protection_rules:
  required_reviewers:
    - Empire325Marketing
  prevent_self_review: true
  dismiss_stale_reviews: true
  require_code_owner_reviews: true
  required_status_checks:
    - "CI Status Check"
    - "Security Scanning"
    - "Code Quality Analysis"
  wait_timer: 5  # 5 minutes
deployment_branch_policy:
  protected_branches: true
  custom_branch_policies: false
variables:
  ENVIRONMENT: production
  LOG_LEVEL: info
  MONITORING_ENABLED: true
secrets:
  # Production secrets should be configured in GitHub UI
  # - DATABASE_URL
  # - API_KEYS
  # - CERTIFICATES
