
version: 2
updates:
  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "Empire325Marketing"
    assignees:
      - "Empire325Marketing"
    commit-message:
      prefix: "🤖"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"
      - "automated"

  # Python dependencies (if requirements.txt exists)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "Empire325Marketing"
    assignees:
      - "Empire325Marketing"
    commit-message:
      prefix: "🐍"
      include: "scope"
    labels:
      - "dependencies"
      - "python"
      - "automated"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Ignore major version updates for critical packages
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  # Node.js dependencies (if package.json exists)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "Empire325Marketing"
    assignees:
      - "Empire325Marketing"
    commit-message:
      prefix: "📦"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
      - "automated"
    versioning-strategy: "increase"

  # Docker dependencies (if Dockerfile exists)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "Empire325Marketing"
    assignees:
      - "Empire325Marketing"
    commit-message:
      prefix: "🐳"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      - "automated"

  # Terraform dependencies (if .tf files exist)
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "Empire325Marketing"
    assignees:
      - "Empire325Marketing"
    commit-message:
      prefix: "🏗️"
      include: "scope"
    labels:
      - "dependencies"
      - "terraform"
      - "infrastructure"
      - "automated"
