
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: primarch-routing

bases:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: dev

patches:
  - target:
      kind: Deployment
      name: litellm
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
  
  - target:
      kind: Deployment
      name: vllm
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/nvidia.com~1gpu
        value: 1

configMapGenerator:
  - name: env-config
    literals:
      - ENVIRONMENT=dev
      - LOG_LEVEL=DEBUG
      - REDIS_HOST=redis
