
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: primarch-routing

bases:
  - ../../base

namePrefix: prod-

commonLabels:
  environment: prod

patches:
  - target:
      kind: Deployment
      name: litellm
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
      - op: add
        path: /spec/template/spec/affinity
        value:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchLabels:
                      app: litellm
                  topologyKey: kubernetes.io/hostname
  
  - target:
      kind: Deployment
      name: vllm
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/nvidia.com~1gpu
        value: 1

configMapGenerator:
  - name: env-config
    literals:
      - ENVIRONMENT=prod
      - LOG_LEVEL=INFO
      - REDIS_HOST=redis
